on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node v4
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: cache npm directory
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }} 

      - name: Install npm ci
        run: npm ci --ignore-scripts

      - name: run npm test
        run: npm test


