on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: setup-node@v4
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: node --version
        run: node --version
      - name: cache@v4
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true  
          fetch-depth: 0    
      - name: Setup actions-hugo@v2
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify --cleanDestinationDir

