on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4

      - name: cache npm directory
        uses: actions/cache@v4
        with:
          path: '**/node_modules' 
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: setup node v4
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'


      - name: Install npm ci
        run: npm install

      - name: run npm test
        run: npm test


