on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache-dependency-path: ~/.yarn.lock
          cache: yarn
      - name: Install node modules
        run: npm ci

      - name: Cache npm directory
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

