name: Hugo

on:
  push:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          # Fetch Hugo themes (true OR recursive)
          submodules: true  
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0    
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      # - name: Install dependencies
      #   run: npm ci
      # https://github.com/marketplace/actions/github-pages-action
      - name: Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        #run: hugo --minify
        run: hugo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
      - name: Ping to Google and Bing
        run: |
          curl -X GET "https://www.google.com/ping?sitemap=https://suzukiiichiro.github.io/google_sitemap.xml"
          curl -X GET "https://www.bing.com/webmaster/ping.aspx?siteMap=https://suzukiiichiro.github.io/google_sitemap.xml"
          # curl -X GET "https://www.google.com/ping?sitemap=https://suzukiiichiro.github.io/index.xml"
          # curl -X GET "https://www.bing.com/webmaster/ping.aspx?siteMap=https://suzukiiichiro.github.io/index.xml"
